version: '3.7'

services:
  document:
    container_name: careecon_document
    image: node:14.3
    working_dir: /careecon_document
    tty: true
    command: /bin/sh -c "yarn && yarn dev"
    volumes:
      - ./:/careecon_document
    ports:
      - '8080:8080'
    logging:
      driver: "json-file" # defaults if not specified
      options:
        max-size: "10m"
        max-file: "3"
